site_name: UArizona HPC Documentation
repo_url: https://github.com/UA-ResearchComputing-HPC/hpc-documentation


nav:
  - Home: index.md
  - HPC Quick Start: 
    - Overview: quick_start/overview/index.md
    - What is HPC?: quick_start/what_is_hpc/index.md
    - Common Misconceptions: quick_start/common_misconceptions/index.md
    - Logging In: quick_start/logging_in/index.md
    - Storage and Transfers: quick_start/storage_and_transfers/index.md
    - Accessing Compute Nodes: quick_start/accessing_compute/index.md
    - Software: quick_start/software/index.md
    - Summary: quick_start/summary/index.md

  - Policies:
    - Acceptable Use: policies/acceptable_use/index.md
    - Access: policies/access/index.md
    - Acknowledgements: policies/acknowledgements/index.md
    - Buy-in: policies/buy_in/index.md
    - Committees: policies/committees/index.md
    - Loss of University Affiliation: policies/loss_of_university_affiliation/index.md
    - Maintenance: policies/maintenance/index.md
    - Special Projects: policies/special_projects/index.md
    
  - Resources:
    - Allocations: resources/allocations/index.md
    - Compute Resources: resources/compute_resources/index.md
    - Research Data Center: resources/data_center/index.md
    - Secure Services: resources/secure_hpc/index.md

  - Access:
    - Account Creation: registration_and_access/account_creation/index.md
    - Account Deletion: registration_and_access/account_deletion/index.md
    - Group Management: registration_and_access/group_management/index.md
    - System Access: registration_and_access/system_access/index.md
    - System Layout: registration_and_access/system_overview/index.md
    - VPN : registration_and_access/vpn/index.md
    
  - Storage and Transfers:
    - Storage:
      - Overview: storage_and_transfers/storage/overview/index.md
      - HPC Storage: storage_and_transfers/storage/hpc_storage/index.md
      - Rental Storage: storage_and_transfers/storage/rental_storage/index.md
      - R-DAS Storage: storage_and_transfers/storage/rdas_storage/index.md
      - Tier2 AWS Storage: storage_and_transfers/storage/tier2_storage/index.md
    - Transfers:
      - Overview: storage_and_transfers/transfers/overview/index.md
      - Open OnDemand: storage_and_transfers/transfers/open_on_demand/index.md
      - Cyberduck: storage_and_transfers/transfers/cyberduck/index.md
      - FTP/LFTP/SFTP: storage_and_transfers/transfers/sftp_ftp_lftp/index.md
      - Globus: storage_and_transfers/transfers/globus/index.md
      - iRODS: storage_and_transfers/transfers/irods/index.md
      - Rsync: storage_and_transfers/transfers/rsync/index.md
      - Rclone: storage_and_transfers/transfers/rclone/index.md
      - SCP: storage_and_transfers/transfers/scp/index.md

  - Software:
    - Overview: software/overview/index.md
    - Modules: software/modules/index.md
    - User Installations: software/user_installations/index.md
    - Common Datasets: software/common_datasets/index.md
    - Popular Software:
      - Anaconda: software/popular_software/anaconda/index.md
      - Gaussian: software/popular_software/gaussian/index.md
      - AlphaFold: software/popular_software/alphafold/index.md
      - Mamba: software/popular_software/mamba/index.md
      - Matlab: software/popular_software/matlab/index.md
      - Perl: software/popular_software/perl/index.md
      - Python: software/popular_software/python/index.md
      - R: software/popular_software/R/index.md
      - VSCode Remote Connection: software/popular_software/vscode_remote_connection/index.md
    - Containers: 
      - What are Containers: software/containers/what_are_containers/index.md
      - Containers on HPC: software/containers/containers_on_hpc/index.md
      - Pulling Containers: software/containers/pulling_containers/index.md
      - Building Containers: software/containers/building_containers/index.md
      - Using Containers: software/containers/using_containers/index.md

  - Running Jobs:
    - Overview: running_jobs/overview/index.md
    - Job Limits: running_jobs/job_limits/index.md
    - CPUs and Memory: running_jobs/cpus_and_memory/index.md

    #- Job Scheduling Guide: 
    #  - Slurm Overview: running_jobs/job_scheduling/slurm_overview/index.md
    #  - Slurm Reference: running_jobs/job_scheduling/slurm_reference/index.md
    #  - Using Your Allocation: running_jobs/job_scheduling/partition_requests/index.md
    #  - GPUs: running_jobs/job_scheduling/gpus/index.md
    - Open OnDemand/Graphical Jobs: running_jobs/open_on_demand/index.md
    - Interactive Jobs: running_jobs/interactive_jobs/index.md
    - Batch Jobs:
      - Intro to Batch: running_jobs/batch_jobs/intro/index.md
      - Batch Directives: running_jobs/batch_jobs/batch_directives/index.md
      - Environment Variables: running_jobs/batch_jobs/environment_variables/index.md
      - Array Jobs: running_jobs/batch_jobs/array_jobs/index.md
      - Jobs with GNU Parallel: running_jobs/batch_jobs/gnu_parallel_jobs/index.md
      - Job Dependencies: running_jobs/batch_jobs/job_dependencies/index.md
      - Submitting Jobs: running_jobs/batch_jobs/submitting_jobs/index.md
      #- Slurm Cheat Sheet: running_jobs/batch_jobs/slurm_reference/index.md
    #- Example Batch Jobs:
    #    - Apptainer Examples: running_jobs/batch_jobs/slurm_reference/index.md
    #   - Array Jobs:
    #      - Basic Array Job: running_jobs/example_batch_jobs/array_jobs/basic_array/index.md
    #      - Array Jobs with Text Filenames: running_jobs/example_batch_jobs/array_jobs/array_read_filenames/index.md
    #      - Array Jobs with Multiple Input Parameters: running_jobs/example_batch_jobs/array_jobs/array_read_parameters/index.md
    #   - General Examples:
    #      - Using a Pipefail: running_jobs/example_batch_jobs/general_examples/pipefail/index.md
    #      - Job Dependencies: running_jobs/example_batch_jobs/general_examples/job_dependencies/index.md
    #      
    - Monitoring Jobs and Resources: running_jobs/monitoring_jobs_and_resources/index.md
    - Parallelization: running_jobs/parallelization/index.md
    # Q is there a way to include the md on the main visualization page instead of in an  "INTRO " sub item?
    - Visualization: 
      - Intro: running_jobs/visualization/index.md
      - Blender: 
        - Blender Command Line Rendering: running_jobs/visualization/blender/command_line_rendering/index.md
        - Scaling Up Blender Rendering: running_jobs/visualization/blender/scaling_up_blender_rendering/index.md
      - ParaView: 
        - Essential Ideas: running_jobs/visualization/paraview/essential_ideas/index.md
        - Getting Started with ParaView GUI: running_jobs/visualization/paraview/getting_started_with_paraview_gui/index.md
        - Advanced Mesh Processing with ParaView GUI: running_jobs/visualization/paraview/cgal_vespa/index.md
        - ParaView Python Plugins: running_jobs/visualization/paraview/paraview_python_plugins/index.md
        - Getting Started with ParaView Terminal: running_jobs/visualization/paraview/getting_started_with_paraview_terminal/index.md
        - Creating Graphs and Exporting Data: running_jobs/visualization/paraview/graphs_and_exporting_data/index.md
        - Cameras and Keyframes: running_jobs/visualization/paraview/cameras_and_keyframes/index.md
        - Headless Batch Rendering: running_jobs/visualization/paraview/headless_batch_rendering/index.md
        - Speeding up Filters & Rendering with Client Server Configurations: running_jobs/visualization/paraview/speeding_up_filters_and_rendering_with_client_server_configurations/index.md
        - Visualizing NetCDF Files: running_jobs/visualization/paraview/visualizing_netcdf_files/index.md
      - ArcGIS Pro Heightmaps: running_jobs/visualization/arcgis_pro_heightmaps/index.md 
      - VisIt: running_jobs/visualization/visit/index.md


  - Support:
    - Consulting Services: support_and_training/consulting_services/index.md
    - Support Staff: support_and_training/people/index.md
    - FAQs: support_and_training/faqs/index.md
        # - Account Access: support_and_training/faqs/account_access/index.md 
        # - General Computing: support_and_training/faqs/general_computing/index.md 
        # - Jobs and Scheduling: support_and_training/faqs/jobs_and_scheduling/index.md 
        # - Software and Modules: support_and_training/faqs/software_and_modules/index.md 
        # - Storage and Transfers: support_and_training/faqs/storage/index.md
        # - Open OnDemand Issues: support_and_training/faqs/open_on_demand_issues/index.md 
        # - Secure Services: support_and_training/faqs/secure_services/index.md    
    # - Workshops: 
    #     - Events Calendar: support_and_training/workshops/events_calendar/index.md
    #     - Intro to HPC: support_and_training/workshops/intro_to_hpc/index.md
    #     - Intro to Machine Learning on HPC:
    #         - Overview: support_and_training/workshops/intro_to_machine_learning/overview/index.md
    #         - Python: support_and_training/workshops/intro_to_machine_learning/python/index.md
    #         - R: support_and_training/workshops/intro_to_machine_learning/R/index.md
    #     - Intro to Parallel Computing: support_and_training/workshops/intro_to_parallel_computing/index.md
    #     - Intro to Containers: support_and_training/workshops/intro_to_containers/index.md
    #     - Intro to Linux: support_and_training/workshops/intro_to_linux/index.md
    #     - Intro to Visualization: support_and_training/workshops/intro_to_visualization/index.md
    #     - Data Management Workshops: support_and_training/workshops/data_management_workshops/index.md
    - Glossary: support_and_training/glossary/index.md
    - Linux Cheat Sheet: support_and_training/cheat_sheet/index.md
    - Grants: support_and_training/grants/index.md
    - Community and External Resources: support_and_training/external_resources/index.md
    - Website Accessibility: support_and_training/website_accessibility/index.md
  
  - Events and Workshops: 
    - Calendar: events/calendar/index.md
    - HPC Workshop Materials: events/workshop_materials/index.md
      # - Intro to HPC: events/workshop_materials/intro_to_hpc/index.md
      # - Intro to Machine Learning on HPC:
      #   - Overview: events/workshop_materials/intro_to_machine_learning/overview/index.md
      #   - Python: events/workshop_materials/intro_to_machine_learning/python/index.md
      #   - R: events/workshop_materials/intro_to_machine_learning/R/index.md
      # - Intro to Parallel Computing: events/workshop_materials/intro_to_parallel_computing/index.md
      # - Intro to Containers: events/workshop_materials/intro_to_containers/index.md
      # - Intro to Linux: events/workshop_materials/intro_to_linux/index.md
      # - Intro to Visualization: events/workshop_materials/intro_to_visualization/index.md
      # - Intro to Statistics: events/workshop_materials/intro_to_statistics/index.md
      # - Data Management Workshops: events/workshop_materials/data_management_workshops/index.md
      # - Managing and Optimizing Jobs: events/workshop_materials/optimization/index.md
  - Blog: 
    - blog/index.md
  - Results: results/index.md
  


markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
      #clickable_checkbox: true

  
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
 
extra_css:
    - assets/stylesheets/extra.css

theme:
  name: material
  logo: assets/images/home/uofa_cactus_computing3.png
  custom_dir: docs/overrides
  favicon: assets/images/favicon.ico
  palette:
    primary: custom
    accent: custom
  icon: 
    annotation: material/star-four-points-circle

  features:
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - toc.integrate
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - navigation.top
    #- announce.dismiss

plugins:
  - blog:
      post_excerpt: optional
  - search

extra:
  analytics:
    provider: google
    property: G-3V0VRBSRZF
    feedback:
      title: Was this page informative?
      ratings:
        - icon: material/thumb-up
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down
          name: This page could be improved
          data: 0
          note: >-
            Thank you for your feedback! Have ideas to improve our site? Please share them in our quick, anonymous <a href="https://forms.gle/WWMkVU66A6pJvmhc9" target="_blank" rel="noopener">feedback form</a>. Your input helps us enhance our documentation!
  generator: false
  social:
    - icon: material/email
      link: https://uarizona.service-now.com/sp?id=sc_cat_item&sys_id=2983102adbd23c109627d90d689619c6&sysparm_category=84d3d1acdbc8f4109627d90d6896191f
      name: Contact HPC consulting
    - icon: material/help-box-multiple
      link: /support_and_training/faqs/
      name: FAQs
    - icon: material/account
      link: https://portal.hpc.arizona.edu/portal/
      name: User portal
    - icon: material/web
      link: https://ood.hpc.arizona.edu/pun/sys/dashboard
      name: Open OnDemand
    - icon: material/youtube
      link: https://www.youtube.com/@universityofarizonauitsres7597
      name: Training videos
    - icon: material/chart-areaspline
      link: https://metrics.hpc.arizona.edu/
      name: HPC job metrics

copyright: University of Arizona Research Computing

